server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:29092
    item-topic: item-topic
  main:
    allow-bean-definition-overriding: true
#    listener:
#      ack-mode: record
#    consumer:
#      group-id: ${spring.application.name}
#      autoOffsetReset: earliest